# Generated by Django 4.0.7 on 2022-09-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('specification', models.CharField(max_length=100)),
            ],
        ),
    ]
